# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HatleyTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HatleyTask

  target 'HatleyTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end
  #Binding
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod  'Alamofire'
  target 'HatleyTaskUITests' do
    # Pods for testing
  end

end
